"""Create tables

Revision ID: 85e50de5b9e9
Revises: 
Create Date: 2024-01-25 10:41:59.496879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85e50de5b9e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('affiliation', sa.String(length=255), nullable=True),
    sa.Column('constituency', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('outcome_status', sa.Boolean(), nullable=True),
    sa.Column('upvotes', sa.Integer(), nullable=True),
    sa.Column('downvotes', sa.Integer(), nullable=True),
    sa.Column('mp_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mp_id'], ['mps.id'], name=op.f('fk_bills_mp_id_mps')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('vote_status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_voting_records_bill_id_bills')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voting_records')
    op.drop_table('bills')
    op.drop_table('users')
    op.drop_table('mps')
    # ### end Alembic commands ###
